licenses(["notice"])  # Apache License 2.0

exports_files(["LICENSE"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logxx",
    visibility = ["//visibility:public"],
    srcs = ["testSo.c"],
    hdrs = ["testH.h"
	       ],
	#  deps = ["//lib:hello-time"]
)

